server:
  port: 9080
  error:
    whitelabel:
      enabled: false

messages:
  home: Hello, Guest!

spring:
  profiles: dev
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
  mvc:
    favicon:
      enabled: false

logging:
  level:
    root: WARN
    com.microfocus: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

